- name: Add Java 7 repository
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present
    update_cache: yes

- name: Add Elasticsearch repository
  vars:
    # 0.90.13 => 0.90
    repoVersion: "{{ es_version|regex_replace('^([^.]*.[^.]*).*', '\\1') }}"
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ repoVersion }}/debian stable main"
    state: present
    update_cache: yes

- name: Install Elasticsearch packages
  apt:
    pkg:
      - openjdk-7-jre-headless
      - elasticsearch={{ es_version }}
    state: present
