- name: Add OpenJDK repository
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present
    update_cache: yes

- name: Install JRE 8
  apt:
    pkg:
      - openjdk-8-jre-headless
    state: present

- name: Install Elasticsearch package
  apt:
    deb: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{es_version}}.deb
